### ISSUE TITLE
Moving jobs to another machine

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1035]
How training job is defined? How can I pack all files needed to define job and corresponding lmdb database and transfer it to another computer and than rerun this job there?

**Comment by gheinrich** [comment]
Hello,
There is no easy way of doing this. The safest thing to do is to re-create everything from the original data. If you give us more context about what you're trying to do we might be able to help.

**Comment by mrgloom** [comment]
1. I want to move DB and training job definition to other computer with more powerfull GPU and run training there to compare speed and results, I'm understand that I can move just data and then create DB and training job manually, but it would be safer when it already created and saved.
2. In more general case I want DB+job definition can be shared between users to reproduce results and to benchmark computers. Or some server(master) can 'emit' jobs and users(workers) can download jobs and data and then execute them and then upload meta data and statistics to server, with such system community of deep learning enthusiast can share their GPU resources to compute some predefined task(or Kaggle competition) with different hyperparameters.

**Comment by gheinrich** [comment]
Once you have created the LMDB on one machine (using DIGITS or not), you can re-create the DIGITS dataset from the LMDB files directly. For this, you need to use the generic dataset interface. For some more background, see the [regression example](https://github.com/NVIDIA/DIGITS/tree/digits-4.0/examples/regression). All of this can be scripted through command line for easy and consistent repro - see the [API](https://github.com/NVIDIA/DIGITS/blob/master/docs/API.md).

**Comment by pkrush** [comment]
I don't work for NVIDIA so I can give you a risky answer:

I have been moving classification Dataset directories machine to machine and it has been working find for me. 

I also clone them outside of DIGITS by editing the job number in the pickle file. 

I also have been creating my own LMDB's and copying them into existing classification jobs. For example I will create a digits job with 1000 files and then copy in LMDB's with 2 million files. You have to manually edit the train and val image totals in 2 places to get this to work. 

You do need to make sure DIGITS is not running because DIGITS saves new copies of pickle files when it shuts down. In other words it will overwrite changes you manually did.

**Comment by lukeyeager** [comment]
This is not a use-case that we support right now. Here are a few things we've done or are working on which are somewhat tangential, but which hopefully address the underlying issue.

When/if we solve https://github.com/NVIDIA/DIGITS/issues/108, you'll be able to run jobs in a cluster from a single control node.
With https://github.com/NVIDIA/DIGITS/pull/896, it's easier to share trained models between machines.
With https://github.com/NVIDIA/DIGITS/pull/1077, it's easier to browse and download from a list of trained models.

**Comment by artmusic0** [comment]
I was once success before when using the old training job, that is packed all the jobs in the job folder(which can find in the config file in digits), and then move to the another digits system.
AND SHOULD BE AWARE OF THE OWNER SHOULD BE SAME AS OLD while you unpack to the new system.
after moving to new system, simply restart the server and you can see the jobs are all coming back.
