### ISSUE TITLE
DetectNet custom dataset 'stabilizes' at extremely low mAP

### ISSUE THREAD

**Issue by rtrahms** [NVIDIA/DIGITS#1211]
Hi all -
I moved from the KITTI DetectNet example to one using my own dataset, a set of images from a soccer match where I have label data around players playing in the match.  Training seems to work (and testing is picking out some (not all) of the players in images after ~80 epochs), but it seems like the mAP should be higher.  Honestly, I don't know what is normal for mAP in object detection, only what it means in classification.

Attached is a screenshot of my training.  Would I expect it to move beyond where it is now?
Thanks,
Rob
![screenshot from 2016-10-23 17 32 57](https://cloud.githubusercontent.com/assets/2120238/19630878/d5aa2ece-9947-11e6-8d67-eed78d60f439.png)

**Comment by lukeyeager** [comment]
DetectNet on KITTI should max out at ~55%. I can't say what values you should expect for your own custom dataset.

Notes about the calculations (DetectNet has some issues):

* The actual mAP value is significantly higher than what is displayed (https://github.com/NVIDIA/caffe/issues/234)
* The precision and recall values aren't really accurate, either (https://github.com/NVIDIA/DIGITS/issues/1112)

Unless you have a bug report or feature request, please direct these inquiries to our user group instead of here on GitHub.
