### ISSUE TITLE
NVIDIA's model store is a dead link

### ISSUE THREAD

**Issue by dbolkensteyn** [NVIDIA/DIGITS#1214]
The link to NVIDIA's model store seems to be dead from this page:
https://github.com/NVIDIA/DIGITS/blob/master/docs/ModelStore.md

`export DIGITS_MODEL_STORE_URL='http://developer.download.nvidia.com/compute/machine-learning/modelstore/4.5.0'`

I'm not getting any pretrained model in DIGITS with this environment variable set, and opening that URL in a browser gives a 404.

**Comment by lukeyeager** [comment]
You're right - we haven't actually set up the official model store yet. We've hit some delays getting the documentation and licensing for each model just right.

/cc @IsaacYangSLA

**Comment by TanLingxiao** [comment]
What is the solution?

**Comment by lukeyeager** [comment]
Until we post the official model store, connecting DIGITS to that URL will do nothing.

For now, you're welcome to follow these instructions to set up your own store:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/ModelStore.md#create-your-own-model-store-server

**Comment by lukeyeager** [comment]
The model store is now live. For now, it contains trained versions of:

* LeNet (MNIST)
* AlexNet (ImageNet)
* GoogLeNet (ImageNet)

We will release more models as they get approved - hopefully a DetectNet (KITTI) will be coming soon!

**Comment by TanLingxiao** [comment]
Thank you for youh notice.I will try soon. 发自网易邮箱大师 在2017年01月25日 02:16，Luke Yeager 写道： The model store is now live. For now, it contains trained versions of: LeNet (MNIST) AlexNet (ImageNet) GoogLeNet (ImageNet) We will release more models as they get approved - hopefully a DetectNet (KITTI) will be coming soon! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by adnphllps** [comment]
Is this offline again? The links to the models on the store page (http://developer.download.nvidia.com/compute/machine-learning/modelstore/5.0) are broken.

**Comment by lukeyeager** [comment]
They aren't broken. The website just isn't set up for browsing. If you connect with DIGITS 5.0 it should all show up OK. e.g. [this link](http://developer.download.nvidia.com/compute/machine-learning/modelstore/5.0/alexnet/info.json) loads fine, but [this one](http://developer.download.nvidia.com/compute/machine-learning/modelstore/5.0/alexnet/) doesn't. DIGITS doesn't need to access the second link in order to download the model.

**Comment by mrasyid** [comment]
I apologize if I missed it somewhere, but how to connect the models link with DIGITS 5.0 ? Thank you.

**Comment by lukeyeager** [comment]
@mrasyid this doc should explain everything you'd want to know:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/ModelStore.md

**Comment by VanitarNordic** [comment]
it seems the model store is offline again.

![screenshot from 2017-04-01 19-54-59](https://cloud.githubusercontent.com/assets/18719591/24579977/55d17e7c-1715-11e7-8e67-80f7075815d7.png)

**Comment by VanitarNordic** [comment]
Okay, updating to the latest repository solved the issue

**Comment by fkhalid** [comment]
With DIGITS 5.0, when I try to access the model store, the following error is generated:

[WARNING] Skip http://developer.download.nvidia.com/compute/machine-learning/modelstore/5.0/ due to error HTTPConnectionPool(host='developer.download.nvidia.com', port=80): Max retries exceeded with url: /compute/machine-learning/modelstore/5.0/master.json (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

And the following message is displayed in the web interface: 'No models in Model Store'.

I am simply interested in accessing the official NVIDIA model store, and therefore, I have not configured my own.

Any suggestions on how to proceed would be great.

**Comment by wlmx** [comment]
@fkhalid check your docker outbound connections settings. Is the problem solved nowadays?

**Comment by fkhalid** [comment]
@wlmx It was indeed a docker network issue. As soon as I started the container with '--net=host', the store became accessible.

Many thanks for your help.
