### ISSUE TITLE
Failed to create object detection model with kitti dataset

### ISSUE THREAD

**Issue by DJmimi35** [NVIDIA/DIGITS#1281]
Hi,

I'm trying to use kitti (http://www.cvlibs.net/datasets/kitti/index.php) to demo Object Detection on my DIGITS server. It's no problem to create kitti dataset. However, it just failed to create model with the following error. It shows the same error when I click "visualize" as well. It looks like something wrong with the custom network file: detectnet_network.prototxt (https://raw.githubusercontent.com/NVIDIA/caffe/caffe-0.15/examples/kitti/detectnet_network.prototxt). I'm wondering if this file has any user guide or update.

caffe version 1.0.0-rc3(BVLC)

500: INTERNAL SERVER ERROR
ParseError
72:3 : Message type "caffe.LayerParameter" has no field named "detectnet_groundtruth_param".

Thanks

Mimi

**Comment by Ali-Maher** [comment]
Hi Mimi , 
I faced this problem before , you should to use NVcaffe  not the head of the caffe repository because it is not included the layers which will be needed for Detectnet like (DetectNetTransformation layer,...) so you need to clone the NVcaffe from https://github.com/NVIDIA/caffe/releases/tag/v0.15.14  and compile it again and make sure to be your CAFFE_ROOT envvar for compiled NVcaffe.

**Comment by AlexandreBriot** [comment]
Hello, 
I met the same problem. 
Then I cloned and compiled nvcaffe 0.15 succesfully.
But still got the same error and when I look at my info in DIGITS, my caffe version is still 0.14.
What should I do to make DIGITS use the right caffe version.
My CAFFE_ROOT envvar has the right path to my new caffe version.
Thanks
Alex

**Comment by DJmimi35** [comment]
Hi, 
It works to me by changing caffe from BVLC to NVIDIA version. 
And my caffe version shows 0.15.14 when I execute "# caffe --version"
But I didn't do anything with the digits setting.
Maybe you should check if your $CAFFE_ROOT point to NVcaffe
Thanks 

Mimi
