### ISSUE TITLE
Training segmentation net fails if any example in the dataset has a label with "ignore" only

### ISSUE THREAD

**Issue by klaimane** [NVIDIA/DIGITS#1285]
Training segmentation net fails if any example in the dataset has a label with "ignore" only.
In this case after training on the "complete-ignore" example the accuracy becomes "nan" and never recovers.

**Comment by gheinrich** [comment]
I think it's easier to discard those samples and not include them in the dataset.

**Comment by gheinrich** [comment]
There is no way to find out whether an image consists of "ignore" labels only during dataset creation since the "ignore" label is set in the model. Some models might work with "ignore-only" labels, some might not. We're trying to avoid doing magical things like you suggest in DIGITS. I will close this issue for now.
