### ISSUE TITLE
Testing a single image 

### ISSUE THREAD

**Issue by samar166** [NVIDIA/DIGITS#1301]
Hello,

I appreciate it if someone explains why the size of the output of the pool1 is [96 27 27] and conv2 is [256 48 5 5]; while pool2 is [256 13 13] and conv3 is [384 256 3 3]? I mean in the first constitutional layer, 256 *48 filters of size 5 by 5 are convolved with 96 images of size 27 by 27, then why 96 is divided by 2 (96/2=48)? 
The scenario is different in pool2 and conv3. In pool2, 256 images of size 13 by 13 are convolved with 384*256 filters of size 3 by 3.

It should be noted that the architecture is AlexNet.
![pool1-conv2](https://cloud.githubusercontent.com/assets/15810187/20661761/85262718-b5a4-11e6-9591-dae4e277b07e.png)
![pool2-conv3](https://cloud.githubusercontent.com/assets/15810187/20662557/00fcfe40-b5a8-11e6-94a1-b2ae243c8cab.png)

**Comment by gheinrich** [comment]
This is because of the [group](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/digits/standard-networks/caffe/alexnet.prototxt#L102) parameter in Alexnet. This is in line with the Alexnet paper: in `conv2` the first half of the filters only "see" the first half of the input feature maps. Similarly the second half of the filters only see the second half of the input feature maps. This is pretty unique to Alexnet. This filter grouping isn't really used in any other popular network.
