### ISSUE TITLE
proto mean substraction in fcn/ segmentation

### ISSUE THREAD

**Issue by RSly** [NVIDIA/DIGITS#1426]
in the segmentation example it reads
* a Power layer was added to shift inputs by -116.0 (in lieu of per-channel mean subtraction)

can anyone explain why -116? should we change this number when training on other datasets?
where to find this number for other datasets created by digits segmentation dataset tool

Also is it exactly equivalent of mean substraction?

**Comment by gheinrich** [comment]
Mean image subtraction is impractical for FCNs because this prevents from taking variable-size inputs. Mean pixel subtraction would work better. In DIGITS you can select `mean pixel subtraction` and remove the `Power` layer.

Applying a fixed offset of `-116` is even simpler and works well enough in practice to keep the data approximately centered around zero. In my experience you usually don't have to tune that parameter to get acceptable accuracy.

Try both methods and see which ones works better for your data.

**Comment by RSly** [comment]
Thanks, I will give it a try.

**Comment by zhuozhongshuo** [comment]
Hi @gheinrich , in  [binary-segmentation] example (https://github.com/NVIDIA/DIGITS/tree/master/examples/binary-segmentation) examples, the introduction recommends us to use 'mean pixel' skill. However, I can not find the mean file (xxx.binaryproto) in that certain created dataset job. What's more, the [segmentation-model.prototxt](https://github.com/NVIDIA/DIGITS/blob/master/examples/binary-segmentation/segmentation-model.prototxt) does not include "mean_value" in data layer, which denotes mean pixel operation.
It is more amazing that when I use pixel mean in pycaffe, the output is extremely poor. Yet, when I feed the input image into the network directly, the output is closer to those in digits.
I am really confused. Could you give me some some advices? Thank you.
