### ISSUE TITLE
What's the difference between the original caffe and NVIDIA caffe ver. 0.10.0? 

### ISSUE THREAD

**Issue by ToruHironaka** [NVIDIA/DIGITS#145]
I have started using DIGITS and I liked it. I think I will install DIGITS on my teammates' machines. Then, this question came up with me. "What's the difference between the original caffe (ver. 0.9999.0: <-- I guess the version) and NVIDIA caffe ver. 0.10.0?" Can you describe the advantage and disadvantage of NVIDIA caffe? Also, What does NVIDIA caffe ver. 0.10.0 have more than the original caffe?

**Comment by lukeyeager** [comment]
The only changes made to the NVIDIA/caffe fork all have to do with versioning. So the `libcaffe.so` becomes `libcaffe-nv.so.0.10.0`. That's valuable for two reasons:

1. DIGITS knows what version of caffe you are using. If you have an outdated version, DIGITS will tell you to upgrade caffe so that it still works with DIGITS.

2. You have some level of assurance that the version of caffe you're using is stable because this version has been built and tested by NVIDIA. When you grab from `BVLC/caffe@master`, you may get unlucky and grab it on a day when something important is broken.

**Comment by ToruHironaka** [comment]
Cool, there is only the library name difference. NVIDIA tests caffe is cool too because I had so many problems when I first install caffe on my machine. 

Actually, I ran DIGIT with the original caffe. It did not work only DIGITS' Test Image operation. Anything else, DGITIS worked work with the original caffe. I reinstalled caffe 0.10.0 to fix this problem. Now, it runs fine.

**Comment by lukeyeager** [comment]
Glad to hear you got it working.
