### ISSUE TITLE
About DIGITS from github 

### ISSUE THREAD

**Issue by ToruHironaka** [NVIDIA/DIGITS#148]
I read article at https://groups.google.com/forum/#!searchin/digits-users/GoogleNet/digits-users/9jsDDd3b1zk/R8S5YgjqPxsJ. You mentioned about new version of DIGITS from https://github.com/NVIDIA/DIGITS has GoogleNet. I clone it and installed requirement. However, it does not run. I initially download and install digits-1.0 from NVIDIA website. This one is still running. Can you tell me how to install github version of digits? or I should not use it.

**Comment by lukeyeager** [comment]
Sorry you're having a problem with your installation - I'll help you figure it out.

But this tracker is for issues with the code. Since your questions has to do with a usage problem, please post on our [digits-users group](https://groups.google.com/d/forum/digits-users). When you do, please provide details about the error that you are getting.
