### ISSUE TITLE
I got aborted dataset and models 

### ISSUE THREAD

**Issue by ToruHironaka** [NVIDIA/DIGITS#149]
Some of my datasets and models completed with Status: Done but some of datasets' and models' status became "Aborted" although they were Status: Done. Why did they become Aborted?

**Comment by lukeyeager** [comment]
Judging from your comments in #148, it sounds like you probably created those datasets and models with DIGITS 1.0, is that correct? There have been several issues fixed since that release, one of which being that jobs were not saved to disk correctly, so when you restart the server they don't get reloaded correctly.

Sorry for the inconvenience, jobs created with a more recent version of DIGITS shouldn't have that problem.

**Comment by ToruHironaka** [comment]
Do you how to reload my jobs manually?

**Comment by lukeyeager** [comment]
Unfortunately that's essentially impossible. You should still be able to use your models, but you'll have to regenerate your datasets.

**Comment by ToruHironaka** [comment]
OK
