### ISSUE TITLE
DIGITS 5 Datasets : ERROR: error code 1

### ISSUE THREAD

**Issue by shoCaffeTeria** [NVIDIA/DIGITS#1540]
I installed DIGITS 5 on Ubuntu14.04 and tried to create dataset(lmdb). But it didn't work. 
I have an error like that,

ERROR: error code 1
File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line59, in <modelu>
MARKER_EXPR = originalTextFor(MARKER_EXPR())("maeker")
TypeError: __call__() takes exactly 2 arguments ( 1 given)

I don't know what happened. What should I do next?
Anyone help?

I have used DIGITS4, there is no problem. 

thanks

**Comment by lukeyeager** [comment]
Looks like a Python dependency problem. I'd Google it.

**Comment by shoCaffeTeria** [comment]
thanks
setuptools seems to have a bug.

**Comment by caleale90** [comment]
> 
ERROR: error code 1
File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line59, in 
MARKER_EXPR = originalTextFor(MARKER_EXPR())("maeker")
TypeError: call() takes exactly 2 arguments ( 1 given)
> 
Is DIGITS that gives you this error or is the content of a log file, because I got the same error (ERROR: error code 1) without any explanation.
I read on the web that could be a dependency problem with Python, but I installed DIGITS through repository and apt-get command, so dependencies should be solved automatically.
