### ISSUE TITLE
Subtract mean file if fine-tuning the pretrained model

### ISSUE THREAD

**Issue by tzutalin** [NVIDIA/DIGITS#186]
Hi, 
  If doing the fine-tuning, it seems DIGITS cannot set specified mean file. For example, if the user would like to fine-tune alexnet and its pretrained model. If the user set "Substract Mean File" to Yes, DIGIT will use the mean file of the selected dataset instead of the mean file of pretrained mode. How can the user specify the mean file of pretrained model?

**Comment by tzutalin** [comment]
I found one the solution is : 
Not set "Subtract Mean File" to YES, and custom network by adding the mean value like bellows. 

transform_param {
    mirror: true
    crop_size: 227
    mean_value: 104
    mean_value: 117
    mean_value: 123
  }

**Comment by lukeyeager** [comment]
Haha, that's a pretty good temporary solution, I guess :smile: 

I'm planning to refactor a lot of the code that creates the prototxt files (in [this awful function](https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc3/digits/model/tasks/caffe_train.py#L115-L118)) so that DIGITS doesn't override your choices for a custom network unless you leave them unset. That should let you do more of what you want in terms of custom networks.

**Comment by tzutalin** [comment]
Ya, my solution is just a workaround.  As you said, I took a look at the snippet of code, save_prototxt_files() is doing too much. By the way, are you planing to do more features for fine-tuning?

**Comment by lukeyeager** [comment]
> are you planing to do more features for fine-tuning?

What would you like? Please create a new issue with your feature request[s]. I'm closing this issue since your question appears to be answered.
