### ISSUE TITLE
can not create database

### ISSUE THREAD

**Issue by blazelisheng** [NVIDIA/DIGITS#23]
Traceback (most recent call last): File "/home/blazeli/digits/tools/create_db.py", line 21, in <module> import leveldb ImportError: No module named leveldb

ps, i've installed leveldb and included the library, caffe is running properly

**Comment by lukeyeager** [comment]
It looks like you're installing from source (cloning GitHub) rather than using the web installer. Is that correct?

Maybe you have installed the lmdb package to your system, but you don't appear to have the python bindings for it. In [the README](https://github.com/NVIDIA/DIGITS/blob/314df8012482091412b35fc31ea2a8f872a4bde1/README.md#install-digits), it asks you to install the python pip dependencies:

    % for req in $(cat requirements.txt); do sudo pip install $req; done

Did you run this command? Did any errors occur?

**Comment by blazelisheng** [comment]
i installed using the web installer, now is working fine. thx
