### ISSUE TITLE
How do I change the "intended image size" on a network?

### ISSUE THREAD

**Issue by mongoose54** [NVIDIA/DIGITS#291]
My images are 50x50 pixels. How do I modify the setting on the networks (i.e. LeNet, AlexNet, GoogleNet) to process them?

**Comment by lukeyeager** [comment]
That's the sort of question that DIGITS won't answer for you, but makes it easier for you to investigate for yourself. That's the sort of question that research teams all around the world try to answer.

If you try to use the default AlexNet network on smaller images, the convolution and pooling layers will try to reduce the spatial dimension of your data to something less than 0, resulting in a cryptic error. For starters, you'll probably want to remove some layers and/or change the `convolution_param` and `num_output` options in the `Convolution` and `InnerProduct` layers, respectively.

If you want to try to design a proper network rather than going through trial and error, I suggest reading the original papers for those standard networks.

**Comment by mongoose54** [comment]
@lukeyeager Thank you for the response. While I fully understand your answer my question had to with the default input nodes of the networks on DIGITS. For example LeNet has an input of 28x28 = 784. While AlexNet and GoogleNet have 256x256 = 65,536. How do I change that input to accommodate a different input image size (e.g. 50x50)? Thanks again.

**Comment by lukeyeager** [comment]
Up to a certain point, you don't have to change anything because the network will adjust to the input size automatically.

I'll try to answer that question with an example. Here are the shapes of the activations for AlexNet run on images with the default size of 227x227. You can see these numbers for yourself in DIGITS if you click on "Show visualizations and statistics" when classifying an image.
```
data    (3, 227, 227)
conv1   (96, 55, 55) 
norm1   (96, 55, 55) 
pool1   (96, 27, 27) 
conv2   (256, 27, 27) 
norm2   (256, 27, 27) 
pool2   (256, 13, 13) 
conv3   (384, 13, 13) 
conv4   (384, 13, 13) 
conv5   (256, 13, 13) 
pool5   (256, 6, 6)
fc6     (4096,)
fc7     (4096,)
fc8     (8,)
```
Here are the shapes of the activations from Alexnet with 200x200 images. By `pool5`, the shape turns out to be the same as for 227x227.
```
data    (3, 200, 200)
conv1   (96, 48, 48) 
norm1   (96, 48, 48) 
pool1   (96, 24, 24) 
conv2   (256, 24, 24) 
norm2   (256, 24, 24) 
pool2   (256, 12, 12) 
conv3   (384, 12, 12) 
conv4   (384, 12, 12) 
conv5   (256, 12, 12) 
pool5   (256, 6, 6)
fc6     (4096,)
fc7     (4096,)
fc8     (8,)
```
For 150x150 images:
```
data    (3, 150, 150)
conv1   (96, 35, 35)
pool1   (96, 17, 17)
conv2   (256, 17, 17)
norm2   (256, 17, 17)
pool2   (256, 8, 8)
conv3   (384, 8, 8)
conv4   (384, 8, 8)
conv5   (256, 8, 8)
pool5   (256, 4, 4)
fc6     (4096,)
fc7     (4096,)
fc8     (8,)
```
As you can see, as the input image size decreases, the network automatically adjusts to fit. This works just up to the point where `pool5` would be `(256, 0, 0)`, at which point you would get an error.

**Comment by mrgloom** [comment]
My 50 cent for this question.
1. In general first layer convolution layers can NOT be large if you use large images (for example 256x256) modern net architectures use small conv 3x3 layers (for example see VGG-16).
2. I have experimented with AlexNet model that shipped with DIGITS with 256x256, 128x128, 64x64 and 32x32 (fail for such small images) and it work best for 256x256 images, for other images it seems to overfitting? Also I don't change default crop size (227x227) maybe it also can cause some problem.

For now best option is to resize input image to 256x256 size?

**Comment by ThienAnh** [comment]
Hi @lukeyeager 

I want to set input size of AlexNet is biger(examlpe: 1000x1000). So how i need to change num_of_output for get no error.

Thank
