### ISSUE TITLE
Address PicklingError for all OS's

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#306]
*See #32 and [this thread](https://groups.google.com/d/msg/digits-users/LFq1OrxM-rU/oWgJp-2CCgAJ)*

People get `PicklingErrors` when trying to pickle protobuf objects. This happens on OSX, but also on Ubuntu 15.04 and even 14.04 in some cases. We should take the fix from 9824be9a7e56d1f375e5deac394527f56e73e99f and use it for all platforms.

**Comment by assaad** [comment]
Yep I suuport this, I get it on Ubuntu 15.04 all the time

**Comment by lukeyeager** [comment]
@assaad, can you try #307 on 15.04 and verify that it works for you?

**Comment by uhfband** [comment]
My system is Centos 7 (64 bit). Recently I encountered pickling errors when I made some experiments with DIGITS and pycaffe. After time  I came to the conclusion that initially this problem was related to the caffe. Protobuf compiler builds python caffe_pb2 module within wrong namespace ('caffe_pb2' instead of 'caffe.proto.caffe_pb2'). Proof:
```
>>> from caffe.proto import caffe_pb2
>>> net = caffe_pb2.NetParameter()
>>> print net.__module__
caffe_pb2
```
DIGITS uses caffe_pb2 as standalone module, and caffe module imports caffe_pb2 as his submodule, so it causes errors when pickling. The solution I found is the importing caffe_pb2 only as submodule.
My patch for DIGITS
https://github.com/uhfband/DIGITS/commit/01d76585fc72d6c567ceb57697bf2bee5d42163e
Patch for caffe-0.15:
https://github.com/uhfband/caffe/commit/eb301a8f603e12b241ff08bd8db4dfdeedccdb84
I hope this information will be useful.
