### ISSUE TITLE
pycaffe incorrect classification comparing to DIGITS

### ISSUE THREAD

**Issue by johnkorn** [NVIDIA/DIGITS#320]
I've trained CNN to classify characters of English alphabet. But during tests I noticed that for some images classification results via DIGITS GUI and via python interface differ.

E.g. below is classification result for sample image in DIGITS:
![class](https://cloud.githubusercontent.com/assets/6063097/9966358/b3ba0100-5e3c-11e5-8018-51d7d1b782f4.png)

Index ```29``` means character ```d```.

Here is python output when classifying the same image:
```FAIL! 18092015170911-613-d.png - expected: 'd', predicted: 'b'; prob: 0.50```

I suppose the issue may be in preprocessing. Below is the code I use to process the image:
```python
    net = caffe.Classifier(MODEL_FILE, PRETRAINED)    
    img = caffe.io.load_image(path+file, color=False)

    grayimg = 255*img[:,:,0]

    gi = np.reshape(grayimg, (32,32,1))

    prediction = net.predict([gi]) 
```
I use binary images, so all pixels are either ```0``` or ```255```.
I did not use mean image while training (```Subtract Mean File``` was set to ```No```)
When I tried to set mean file to classifier:
```python
blob = caffe.proto.caffe_pb2.BlobProto()
data = open(MEAN_FILE, 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )

net = caffe.Classifier(MODEL_FILE, PRETRAINED, mean=arr[0])
```
classification result was even worse.
What could cause such mistakes?

**Comment by lukeyeager** [comment]
I suggest using `caffe.io.Transformer` instead of doing the transformations manually. As an example, see what is done in `examples/classification/example.py`:

https://github.com/NVIDIA/DIGITS/blob/v2.2.1/examples/classification/example.py#L40-L49

In your case, I suspect [`np.reshape`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) doesn't do what you think it does. You might be looking for [`scipy.misc.imresize`](http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.misc.imresize.html).

**Comment by AntreasAntoniou** [comment]
Yes, I agree with lukeyeager. I had a similar issue with another framework. When you use reshape, instead of creating an image using 1 channel for each colour it just mixes them all together and starts reading to fill up the shape of the numpy array. To make sure this is the case try using plot.imshow and plot.show() to see what your images really look like

**Comment by johnkorn** [comment]
Thanks for the help. I've tried to do the same preprocessing as in example.py (with imresize and transformer). And it solved my problem. And network accuracy appeared to be much better!
