### ISSUE TITLE
Automatically prune GoogleNet useless branches in the deploy

### ISSUE THREAD

**Issue by borelien** [NVIDIA/DIGITS#335]
Loss1 and loss2 branches are not used anymore at test time, but included in the deploy. It could be nice to prune them automatically to speed up the forward.

**Comment by lukeyeager** [comment]
Good point. Since #189, we can exclude layers from inference by changing the names of those layers from `name` to `train_name`.

The models will still be bloated with the weights for the other two branches, but it should speed up inference.

@borelien, do you want to try this out and verify that it helps?

**Comment by lukeyeager** [comment]
Oh right, actually #189 only added that feature for specifying generic models, not for classification models. My bad. Let me look into how much work that would be ...
