### ISSUE TITLE
Feature request: Output list training files after shuffling 

### ISSUE THREAD

**Issue by antran89** [NVIDIA/DIGITS#386]
Hi developers,
I think it is more useful to output list of files in the database **after** shuffling rather than **before** shuffling. The files will help DIGITS users to see mapping between image files and the data stored inside database.
Thanks,
@An

**Comment by lukeyeager** [comment]
Thanks for the feature request!

I'm not totally convinced we should do this yet.

1. I sometimes like to have access to the unshuffled lists because I can edit them manually (remove a class, duplicate all images in a class, etc.) and re-upload them
2. It doesn't seem like a good idea to store BOTH textfiles and take up extra space

Maybe you can expand on the problem that you'd like to solve? When/why do you want to do this?

> The files will help DIGITS users to see mapping between image files and the data stored inside database.

Also, check out #331.

**Comment by antran89** [comment]
Thanks @lukeyeager,
At that time, I experienced that the order of shuffling affects the accuracy. So I am curious to see what the shuffled data looks like. 
Thank for the reply. I think I will close the ticket.
