### ISSUE TITLE
is storage format different in lmdb created by digits?

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#43]
I wanted to create a confusion matrix by reading the test data from lmdb created by digits. i had a old script which reads the data from lmdb as datum and does it. but it is not working now.

Are the data format in lmdb created by caffe and digits different? 
Caffe stores them as datums and looks like digits stores them as jpeg. 

is it possible to maintain compatibility between storage formats?

**Comment by lukeyeager** [comment]
> looks like digits stores them as jpeg

The code I use to create the `Datums` is [here](https://github.com/NVIDIA/DIGITS/blob/v1.0.1/tools/create_db.py#L358-L383). DIGITS is still storing them as `Datums`, but `datum.data` is a JPEG string, and `datum.encoded` is turned on.

If your old script doesn't work, it probably was written against the old caffe Datum format (before the `encoded` flag got added). JPEG encoding is awesome - it cuts the size of the dataset down considerably, which is super helpful if you're building all of ImageNet. 

That being said, **you can disable JPEG encoding when you create your dataset** (it's turned on by default), if that makes it easier for you to do other things with the dataset.

> is it possible to maintain compatibility between storage formats?

I'm not sure what you're getting at, exactly. But I am considering moving to using HDF5 as the default backend because LMDB/LevelDB don't work for some of the other data formats like audio or video. Also, I don't want to require a caffe-specific data format when DIGITS is planning to support multiple framework backends. More on all that to come soon.

**Comment by jmozah** [comment]
Cool... thanks for the explanation.
