### ISSUE TITLE
when will you release digits for windows, 

### ISSUE THREAD

**Issue by caffeTao** [NVIDIA/DIGITS#47]
there's one caffe-windows  at http://pan.baidu.com/s/1eQ6bWK6

**Comment by lukeyeager** [comment]
Windows is [not officially supported](http://caffe.berkeleyvision.org/installation.html#windows) even in Caffe. I've done my best to keep the code in DIGITS platform-independent though (with a few exceptions, like in `digits.config`), so it shouldn't be too much work to get it running. At present, however, there is no plan to begin supporting Windows. If you do try to implement it yourself, I would love to hear how it goes and would be happy to provide any advice that I can.

**Comment by Coderx7** [comment]
@lukeyeager : Caffe is supported on windows by Microsoft now. check the official branch here : https://github.com/Microsoft/caffe
now I guess porting Digits to windows is rather easy compared to the time, caffe was'nt on windows!

**Comment by lunzueta** [comment]
@Coderx7 That's right. I've already tried to use Digits on Windows with that Windows Caffe version and I could do it (check the last comment here: https://github.com/willyd/caffe-builder/issues/6)

**Comment by Coderx7** [comment]
@lunzueta : Great job ;) 
now I'm impatiently waiting for your guide on how to get DIGITS to work on windows ;)

**Comment by lunzueta** [comment]
@Coderx7 Probably not the best way, but here is a very brief guide of what I did:

1) Install Python. In my case, I installed Anaconda (https://www.continuum.io/downloads). Optionally, you can also install PyCharm (https://www.jetbrains.com/pycharm/) to configure and run the Python projects in a more visual way.
2) Install Graphviz for Windows (http://www.graphviz.org/Download_windows.php) and include its bin directory in the 'path' environment variable.
3) Checkout the 'windows' branch of Caffe (https://github.com/BVLC/caffe/tree/windows) and compile it (quite straightforward to do this, just follow the instructions explained there).
4) Include the 'caffe' folder generated when compiling 'pycaffe' (the one inside the 'CAFFE_PATH\Build\x64\Release\pycaffe' folder), in the folder 'C:\Anaconda2\Lib\site-packages', so that Caffe can then be imported as an external library in your Python project.
5) Checkout Digits from its Github repo.
6) Open a Windows Command Prompt, go to the folder where Digits is installed and run this: `python -m pip install -r requirements.txt`
7) Then, run this: `python digits-devserver` and you'll be able to see Digits on http://localhost:5000 and use it normally. I wasn't able to run the 'digits-server' bash file yet, but I guess this can also be "windows"-ized with some more dedication.

Hope this helps.

**Comment by Coderx7** [comment]
Great job indeed ;) 
Thanks a gazillion ;-)

**Comment by Coderx7** [comment]
@lunzueta : I'm getting an error when I try to run digits-devserver, 
```
T:\DIGITS-master>python digits-devserver
Default value for caffe_root "<PATHS>" invalid:
        caffe binary not found in PATH
==================================== Caffe =====================================
Where is caffe installed?

        Suggested values:
        (P*) [PATH/PYTHONPATH] <PATHS>
```
I Imported caffe successfully,and also added the caffe bin directory (Build\X64\Release\pycaffe\caffe) as well, yet this error is happening. 
I would really appreciate a guidance here. 
Thanks in advance

**Comment by lunzueta** [comment]
@Coderx7 Hi. Now I'm testing all this in another PC to be sure that I didn't miss anything in the explanation above, but I'm still on it. Maybe this is happening because you should also add this directory to the 'path' environment variable: 'CAFFE_PATH\Build\x64\Release'. Let me know.

**Comment by Coderx7** [comment]
@lunzueta :Hi, Actually I have set the `Path` environment variable as well, this actually looks like this:
`%CAFFE_ROOT%\pycaffe\caffe;%CAFFE_ROOT%`
in which `CAFFE_ROOT` is a user variable with the value of : `T:\Caffe\Build\x64\Release`. 
I also tried logging off and even restarting my PC, still no luck.
should I add caffe to the python path as well? I'm not a python coder you know!

**Comment by happynear** [comment]
@Coderx7 , I modified the `./digits/config/caffe_option.py`, line `87` to let DIGITS know where the `caffe.exe` is. Then modify line `197` from `parse_version(0,11,0)` to `parse_version(0,12,0)` to let DIGITS know that the `caffe.exe` is built by Visual Studio 2013. Hope these hints would help you.

**Comment by Coderx7** [comment]
@happynear : Thanks alot , the server is now running. but I dont know if this is related to this or not. 
I tried running the main.py in order to download the mnist dataset and give it a try, but I get the few parameters error . 
I am doing it like this : 
`T:\DIGITS-master>tools\download_data\main.py mnist /mnist
usage: main.py [-h] [-c] dataset output_dir
main.py: error: too few arguments`

and this : 
`T:\DIGITS-master>tools\download_data\main.py mnist  T:\DIGITS-master\mnist
usage: main.py [-h] [-c] dataset output_dir
main.py: error: too few arguments`
which as you can see doesnt work!. 
by the way the mnist folder is there , so I dont know whats causing this!

**Comment by lunzueta** [comment]
@Coderx7 I've just installed everything in another PC, following the "brief guide" I explained above, and also including 'CAFFE_PATH\Build\x64\Release' in the 'path' environment variable, and I could also run it correctly. @happynear why are those modifications you mention needed?

**Comment by Coderx7** [comment]
@lunzueta : I dont know, I just followed what you said and that didnt work for me, I added the caffes release  folder and its executable path plus the address of the caffe folder inside pycaffe folder and nothing worked! until I did as @happynear suggested. 

By the way I'm facing some weird issues at the moment. 
the server is running just fine. 
I can easily create the mnist dataset 
but when I try to create a model and train the mnist dataset it fails! 

```
Train Caffe Model Error

    Initialized at 10:40:46 PM (1 second)
    Running at 10:40:48 PM (0 seconds)
    Error at 10:40:48 PM
    (Total - 1 second)

ERROR: [Error 2] The system cannot find the file specified

Traceback (most recent call last):
  File "T:\DIGITS-master\digits\scheduler.py", line 484, in run_task
    task.run(resources)
  File "T:\DIGITS-master\digits\task.py", line 202, in run
    env=env,
  File "L:\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "L:\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```
Dont know whats going on here :-/ !

**Comment by Coderx7** [comment]
Ok, I deleted everything and started from scratch. 
I installed Anaconda2 ( the latest version ) . 
Followed @lunzueta 's guide and then applied the @happynear 's modification actually in two places inside caffe_options.py (line 114 and 210 like following):
line 114: `executable = 'T:/Caffe/Build/x64/Release/caffe.exe'#os.path.join(path, program)`
line 210: `executable = 'T:/Caffe/Build/x64/Release/caffe.exe'#os.path.join(value, 'build', 'tools', 'caffe')`
and I didnt change anything else (didnt need to change line 196 (`return parse_version(0,11,0)` )
and to my astonishment, everything is working just fantastic! 
Thanks again guys . 
(by the way I noticed when I tried to use `Show visualizations and statistics`, python.exe crashed. if I uncheck it and classify everything is fine. but with that option checked the python crashed. Any Idea on this?

**Comment by lunzueta** [comment]
@Coderx7 Good to know it worked in your side too. Meanwhile, I did some more tests in my side comparing what I could get in Linux and also in Windows. Mnist + LeNet worked in the same way in both, except when I marked the option "Show visualizations and statistics" for testing. In Windows it crashed. So, I guess that we still can't say the compatibility issue is completely solved. I'm not sure if this is because of Digits code or because of the Caffe version we are using, which isn't Nvidia's Caffe fork.

**Comment by lunzueta** [comment]
@Coderx7 Good to know that it also worked in your side. Yes, I also got that error you mention when `Show visualizations and statistics` is activated when testing. So, I guess we still can't say that the compatibility issue is completely solved. I don't know if this happened because of Digit's code or because we aren't using Nvidia's Caffe fork.

**Comment by Coderx7** [comment]
@lunzueta yes, you are right. I couldn't either use debugging to know for sure whats going on. 
I listened to your suggestion and installed Pycharm the community edition, but when ever I tried to run debug! everything froze! tried it for couple of times, yet nothing changed. the same thing made me use print and log for debugging ! and you saw how that turned out!
dont know what the problem is though. If debugging worked, I'm 100% sure we could figure out the cause much sooner.

**Comment by IsaacYangSLA** [comment]
There might be a temporary solution.  If I loaded h5py before caffe, the problem seemed to disappear.  The hdf5 DLL loaded by h5py and Caffe were different.  h5py is using a newer version, while the one in nuget (for Caffe) is old.

**Comment by thanghn90** [comment]
Hello! This is my first post in github, so please forgive me if I did sth wrong.

Hmm... Strange, I followed @lunzueta  guide and everything is working for me! (Including the Show visualizations and staticstics).
Here is what I have done:
1. I compiled caffe from @happynear's branch (follow his exact instruction, especially the python wrapper stuff):
https://github.com/happynear/caffe-windows
2. I downloaded Anaconda2 as my python. Installed it, got an error that need to be ignored at the end of the installation, but somehow it still works for me.
3. Pycaffe from happynear branch has some requirement. I have to remove level-db and protobuf from the requirement.txt under caffe-windows-master/python, do a pip install just like @lunzueta said (for pycaffe, NOT for DIGITS, that's a later step). Then I followed @happynear to recompile level-db and install protobuf manually (the instruction is in @happynear 's caffe branch in the link above).
4. I made sure to correctly modified the python include and python library path in happynear's caffe Visual studio project to point them to Anaconda2 include and libs directories. Then I compile pycaffe.
5. I then copied the caffe folder under caffe-windows-master/python to Anaconda2/Lib/site-packages.
6. Then I download DIGITs repository:
https://github.com/NVIDIA/DIGITS
7. Again, I check the requirements.txt under DIGITS-master/ and make sure to remove level-db or protobuf. Then pip install the requirements.
** NOTE ** For pip install to work smoothly, I have to install Visual C++ for Python:
https://www.microsoft.com/en-us/download/details.aspx?id=44266
And also create a bat file with all the required paths to binaries and dlls, then run the bat file as ADMINISTRATOR. The content of the bat file for DIGITS-master python requirements.txt is:

REM If this bat file is run as administrator,
REM the program will start from %SystemRoot%\System32
REM Thus, first go to the folder where the bat file is run
cd /D %~dp0

PATH=.;^
..\Anaconda2;^
%SystemRoot%\System32;^
%SystemRoot%

python.exe -m pip install -r requirements.txt

pause

Forgot to mention: you need a similar bat file for pycaffe's requirements.txt.
8. The key difference is that** I don't modify caffe_options.py**. Instead, I created a bat file that contain the paths to all required binaries and dlls. One thing I noticed is that somehow the PATH environment for digits-devserver MUST BE ABSOLUTE PATH, meaning you can't use "..\". The content of digit server running bat file is:

REM If this bat file is run as administrator,
REM the program will start from %SystemRoot%\System32
REM Thus, first go to the folder where the bat file is run
cd /D %~dp0

PATH=.;^
D:\University of Oklahoma\Projects\Caffe\Anaconda2;^
D:\University of Oklahoma\Projects\Caffe\caffe-windows-master\3rdparty\bin;^
D:\University of Oklahoma\Projects\Caffe\caffe-windows-master\bin;^
D:\University of Oklahoma\Projects\Caffe\Graphviz2.38\bin;^
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin;
%SystemRoot%\System32;^
%SystemRoot%

python.exe digits-devserver

pause

Here I put DIGITS-master, Anaconda2, caffe-windows-master, and Graphviz2.38 into one single place called D:\University of Oklahoma\Projects\Caffe. The bat file is named run_digit.bat and is put in D:\University of Oklahoma\Projects\Caffe\DIGITS-master.

After that, everything is working (except Torch, which I can't find any source to compile on Windows using Visual Studio, but it's not required anyways).

FYI, I'm compiling caffe with compute capability of 30 (I have GTX 660 card). I tested it on both Windows 7 and Windows 10 Enterprise 64 bit. I guess "Show Visualization and statistics" option doesn't work for you guys because you modified the caffe-options.py?

**Comment by IsaacYangSLA** [comment]
Thanks for the information.  I built my caffe from https://github.com/microsoft/caffe, and installed Python 2.7.11 64-bit from official Python site.  The h5py package was from UCI's unofficial python package site.

**Comment by monkeyonagazeboo** [comment]
Hi, 
first, thank you all for the hard work to port DIGITS to win. 
I followed the guides mentioned in this thread, repeated the installation process several times, but everytime I get following error while running training (I had no trouble creating lmdb sets): 

Traceback (most recent call last):
  File "d:\Toolkits\DIGITS\digits\scheduler.py", line 484, in run_task
    task.run(resources)
  File "d:\Toolkits\DIGITS\digits\task.py", line 250, in run
    self.after_runtime_error()
  File "d:\Toolkits\DIGITS\digits\model\tasks\caffe_train.py", line 937, in after_runtime_error
    output = subprocess.check_output(['tail', '-n40', self.path(self.CAFFE_LOG)])
  File "C:\Anaconda2\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified


Unfortunatelly I'm no pythonist so I have no clue how to resolve this. I'm using the Microsoft caffe branch successfully for some time now and it alone is working fine. It'd be nice to have some gui though :)

BTW. I know that caffe.exe is accessible from the caffe_output.log. So the problem is probably somewhere else.

Does anybody have the same issue ?

**Comment by Coderx7** [comment]
`The system cannot find the file specified` error indicates it can not find your caffe, at least this was in my case. 
try using the full path for caffes executable, or use the one I myself used! [here  ](https://github.com/Coderx7/DIGITS-WINDOWS) 
hope this helps

**Comment by monkeyonagazeboo** [comment]
@Coderx7 Thank you. Actually I set the path to caffe.exe explicitly (edited the lines 114 & 210 as you suggested in your comments ). And by checking the caffe_output.log file I can see that the network is configuring ( ie caffe.exe is running ) and than stops suddenly before the training starts : 
...
I0507 21:05:03.662497 10716 net.cpp:217] pool2 needs backward computation.
I0507 21:05:03.662497 10716 net.cpp:217] norm2 needs backward computation.
I0507 21:05:03.662497 10716 net.cpp:217] relu2 needs backward computation.
I0507 21:05:03.662497 10716 net.cpp:217] conv2 needs backward computation.
I0507 21:05:03.662497 10716 net.cpp:217] pool1 needs backwar*** Check failure stack trace: ***

thanks for the link. I'll give it a try...

**Comment by monkeyonagazeboo** [comment]
@Coderx7 So I checked out your repo, followed your instructions (changed the paths to executable in digits config, made sure all path variables are set correctly, I even have caffe.exe folder in path for sure ), but the problem persists. I will probably start once again from scratch, but I'm skeptical. BTW, when including pycaffe to Anaconda2 site-packages, do you just copy the whole caffe folder (located in /caffe/build/x64/Release/pycaffe/) to site-packages folder? Also do you use 32bit or 64bit installation of Anaconda? 
Thanks for your help.

**Comment by Coderx7** [comment]
@monkeyonagazeboo : yes the contents of pycaffe need to be copied to site-packages folder. 
I'm using Anaconda 64bit (2.7 I guess)

**Comment by monkeyonagazeboo** [comment]
I don't know. Once more I uninstalled/deleted everything (caffe, digits, anaconda), re-installed and re-build using the @lunzueta guide, but the problem stays the same. Next time I will try another machine, after I get some. Thanks for your time.

**Comment by Coderx7** [comment]
I hope you figure it out soon. 
Good luck ;-)

**Comment by monkeyonagazeboo** [comment]
@Coderx7 So I have found out what the problem was. The machine I was testing digits on has graphics card with less graphic RAM and the caffe training was failing with cuda out of memory error. This can be easily seen by running the same solver from command line. By using the smaller batch size the error disappeared. I don't understand why is the digits failing with 'File not found' instead of CUDA out of memory message, but everything seems to work fine now, including the visualization and statistics feature. Thank again for your support.

**Comment by Coderx7** [comment]
@monkeyonagazeboo I'm glad to hear you made it as well ;-)

**Comment by andrewssobral** [comment]
any news about this? someone successfully ran DIGITS on windows?

**Comment by Coderx7** [comment]
@andrewssobral: we all did! read the posts and you will know the process.

**Comment by JVR32** [comment]
Hello,

Although I followed some of the instructions in this thread, I’m still struggling with getting DIGITS to work using Windows.

I use following caffe-version : [https://github.com/BVLC/caffe/tree/windows]
And I try to use DIGITS 3.

Building caffe was successful, and caffe is running using a command prompt or powershell.

But when I launch **python digits-devserver** in a command prompt, it fails with following message :

**'Your Caffe does not have version info.  Please upgrade it.'**

And it also produces : **‘Where is caffe installed’ ?**

So, since I told the location of the executable (‘C:\Programs\caffe-windows\Build\x64\Release\caffe.exe’), I suppose that the main problem is that he cannot get a version while executing `info_dict = cls.get_info(executable)` (line 154 in caffe_option.py)

Does anyone know what I could try more to fix this problem?

Thanks in advance.

**Comment by thanghn90** [comment]
@JVR32 : Hello! I'm not sure you read my post yet, but it seems like DIGITS changes working directory while running, so you probably want to make a .bat file like I said in my previous post and include the absolute path to your caffe.exe.
The error "not have version info" is probably because you have not copied the compiled caffe python library into your python site packages location (in my downloaded caffe visual studio solution, there is a caffe-python project, which you need to make sure you can compile).

Again, please spend some time reading my post. I know it's long, but I'm sure it works.
Hope that helps!

**Comment by JVR32** [comment]
Was able to start it be making another change to _caffe_option.py_

Replaced `version_string = line[line.find(pattern) + len(pattern)+1:].rstrip()` by `version_string = '0.12.0'` in `get_executable_version_string()`

Already had replaced 0.11.0 by 0.12.0 in that file before asking my previous question, but apparently on the wrong location. Now that problem seems to be solved.

However, [http://localhost:5000] provides the interface, but now I got stuck on another -rather annoying- obstacle : when I want to configure my experiment, I want to provide the folder where the training images are stored -> New Image Classification Dataset -> Training Images (= " Indicate a folder which holds subfolders full of images"). I should expect that I must add e.g. 'c:/temp/images', but that's not possible. He always adds another '/' in front (-> /c:/temp/images) and always says 'training images - folder does not exist' when pressing 'create'-button on that page. And a browse-button to select a folder is not provided  :-(   So I have to find a way to select the folder that contains my training images.

**Comment by gheinrich** [comment]
> He always adds another '/' in front

Whoops, that's probably a consequence of https://github.com/NVIDIA/DIGITS/pull/773 and this [line](https://github.com/NVIDIA/DIGITS/blob/v4.0.0-rc.1/digits/templates/layout.html#L87). You might want to remove it while we fix it.

**Comment by JVR32** [comment]
@gheinrich : removing that line solved the problem. Thank you!

**Comment by lukeyeager** [comment]
> And I try to use DIGITS 3.

You're going to want to use v4.0.0-rc.1 to include @IsaacYangSLA's Windows fixes:
https://github.com/NVIDIA/DIGITS/pull/769, https://github.com/NVIDIA/DIGITS/pull/781, etc.

**Comment by chris-hawley** [comment]
is there an updated guide for doing this or is it still broken?

**Comment by lunzueta** [comment]
@chris-hawley https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigitsWindows.md

**Comment by conner99** [comment]
Updated guide for Miniconda Python
https://github.com/conner99/DIGITS/blob/master/docs/BuildDigitsWindows.md

**Comment by Chachay** [comment]
Thank you for the helpful installation guide!
I found just one thing at the part of 

’’’
python -m pip install -r requirements.txt
’’’

This command made all file names into lower case with the latest pip script (8.1.2 on windows 10), which led small messes. 
E.g. PIL/Image.py into pil/image.py

I had to reinstall pillow ( and edit some lines in later requirement.txt too )

**Comment by DiegoHerrera1890** [comment]
Hello Everyone. Thanks for all your post.
Perhaps is too late... but I'm trying to run Digits in Windows 10.
I followed all the steps, but I'm Stuck here:

`
C:\Windows\System32\DIGITS>python -m digits
![error](https://user-images.githubusercontent.com/45737011/52027525-19fa7800-254f-11e9-96ac-152a09aade75.PNG)

C:\Program Files\Anaconda3\lib\site-packages\gevent\monkey.py:395: RuntimeWarning: Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
_warnings)
Traceback (most recent call last):
File "", line 969, in _find_and_load
File "", line 958, in _find_and_load_unlocked
File "", line 673, in _load_unlocked
File "", line 665, in exec_module
File "", line 222, in _call_with_frames_removed
File "C:\Windows\System32\DIGITS\digits\webapp.py", line 25, in 
app.config['SECRET_KEY'] = os.urandom(12).encode('hex')
AttributeError: 'bytes' object has no attribute 'encode'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\Anaconda3\lib\runpy.py", line 184, in run_module_as_main
"main", mod_spec)
File "C:\Program Files\Anaconda3\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Windows\System32\DIGITS\digits_main.py", line 70, in 
main()
File "C:\Windows\System32\DIGITS\digits_main.py", line 55, in main
import digits.webapp
File "", line 969, in _find_and_load
File "", line 171, in exit
File "", line 123, in release
RuntimeError: cannot release un-acquired lock




`

**Comment by Coderx7** [comment]
@DiegoHerrera1890 :
Check out this guide for windows : https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigitsWindows.md
in case the latest version doesn't work, use an older version around the same time frame from here : https://github.com/NVIDIA/DIGITS/releases
I guess you should be fine now
