### ISSUE TITLE
caffe BGR issue

### ISSUE THREAD

**Issue by dxj19831029** [NVIDIA/DIGITS#52]
hey,

After I trained the model successfully, I tried to test one image, and I found it does not do channel swap. So I am a little confused.

Here is my understanding:

Inside caffe, if you let caffe do decoding on the image, it will always be BGR format(by opencv). And I did not see any code inside digits, which will convert loaded images into BGR mode. Therefore,

digits create db -----> with encoded images
caffe train the db ------> with BGR format
digits test one image -------> with RGB format

So the final result won't work as expected.

Did I miss anything?

**Comment by lukeyeager** [comment]
Rats. I intentionally avoided swapping channels because it's annoying and because I want the datasets to be consumable by different deep-learning frameworks which don't require the channel swap. It was all working fine until I added the JPEG compression.

I think the right thing to do is to do the channel swap at inference time only if the dataset was encoded and chalk this up to a caffe "bug".

Thanks very much for bringing this to my attention, @dxj19831029.
