### ISSUE TITLE
AlexNet 96 filters, 64 activations

### ISSUE THREAD

**Issue by cmis91** [NVIDIA/DIGITS#63]
should the # of activations matches # of filters since one activation is the image after applying filter on the previous layer map. 

![image](https://cloud.githubusercontent.com/assets/9816523/7102304/d5597b5e-e030-11e4-9348-77e0d4919c93.png)

**Comment by lukeyeager** [comment]
There are actually 96 activations, but I'm not displaying all of them. I'm doing is cutting down the number of activations/weights to a max width of 500px (chosen fairly arbitrarily). That's basically what caffe does in their [filter visualization example notebook](http://nbviewer.ipython.org/github/bvlc/caffe/blob/master/examples/filter_visualization.ipynb).

Since the weights are smaller (in terms of WxH), more of them fit on the page. If you have any other suggestions about better ways to visualize the filters, I'm all ears. Would it be helpful to have a little message somewhere that says "64 of 96 shown"?
