### ISSUE TITLE
DIGITS not refresh screen again

### ISSUE THREAD

**Issue by ssilphf** [NVIDIA/DIGITS#643]
Problem:
I had reinstalled all my system right now.
There is a problem that DIGITS not refresh screen again.
Similer with #415, but not caused by `Flask-SocketIO==0.6.0` this time.

Resolution:
I set my `requirements.txt` as:

> Pillow==2.3.0
numpy==1.8.2
scipy==0.13.3
protobuf==2.5.0
six==1.5.2
requests==2.2.1
gevent==1.0
Flask==0.10.1
Flask-WTF==0.11
wtforms==2.0.0
Flask-SocketIO==0.6.0
gunicorn==17.5
setuptools==3.3
lmdb==0.87
h5py==2.2.1
pydot2

and do `for req in $(cat requirements.txt); do sudo pip install $req; done` again
then DIGITS can refresh screen for me now.

I think this problem maybe caused by the library upgrading in the list, 
but I don't caused by which library.

**Comment by lukeyeager** [comment]
You've posted the list of versions that work? That's not very helpful. Can you post the versions which cause the issue?

Also, which instructions are you following that are still using the shell for loop?
https://github.com/NVIDIA/DIGITS/blob/v3.2.0/docs/BuildDigits.md#python-packages

**Comment by ssilphf** [comment]
I had try to upgrade all of the list to the last version one by one.
This problem maybe caused by gevent1.1.
There is a new uploaded on at 2016-03-12.
Please have a look of under URL.
https://pypi.python.org/pypi/gevent

**Comment by PhoenixDai** [comment]
I think I also got the same problem and finally I figured out it's caused by gevent=1.1b4 with the following error:
Traceback (most recent call last):
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/socketio/handler.py", line 122, in handle_one_response
    return self._do_handshake(handshake_tokens.groupdict())
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/socketio/handler.py", line 64, in _do_handshake
    self.write_smart(data)
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/socketio/handler.py", line 88, in write_smart
    self.write_plain_result(data)
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/socketio/handler.py", line 78, in write_plain_result
    ("Content-Type", "text/plain"),
  File "/raid/qdai2/tools/anaconda2/lib/python2.7/site-packages/gevent/pywsgi.py", line 778, in start_response
    raise UnicodeError("The value must be a native string", header, value)
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x7ff184efaa50: _handle_and_close_when_done(<bound method SocketIOServer.handle of <SocketIOSe, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7ff194b97510 fileno=[Errno 9] Bad fi)> failed with UnicodeError

After I downgrade gevent to 1.0, it works well.

**Comment by lukeyeager** [comment]
You're right, it looks like the latest version of `gevent` doesn't play nice with [python-socketio](https://github.com/miguelgrinberg/python-socketio). @PhoenixDai I'm seeing the exact same error with any `gevent` version greater than 1.0.2.

**Comment by enoonIT** [comment]
Doing pip install `gevent<=1.0.2` fixed the issues for me. Shouldn't the requirements file be updated to enforce this?

**Comment by lukeyeager** [comment]
@enoonIT you're right. I thought that `1.1.0` was safe but I didn't realize I was actually using `1.0.1` from a pip installation instead of `1.1.0` that I installed with a deb package on 16.04. When I remove the pip installation I can see that `1.1.0` causes problems.

Filed new bug at #929.

**Comment by SergeyBykov1** [comment]
I'd like to confirm the same issue on Windows.
Digits 4.0, OS Windows 7 x64, all steps from BuildDigitsWindows.md
Using gevent-1.1.2 results in "must be a native string" error and no autorefresh.
Installing gevent=1.0 solves the issue, but also requires a simple install of MS VC++ for Python2.7 (http://aka.ms/vcpython27)
