### ISSUE TITLE
Cloning a renamed job uses the old name

### ISSUE THREAD

**Issue by flx42** [NVIDIA/DIGITS#710]
1. Create a job (dataset or model) and call it "A"
2. Rename the job to "B"
3. Use "Clone Job"
4. The default name for the cloned job is the original "A", instead of B.

Annoying when I accidentally called a job "CIFAR Color" but instead it should be "CIFAR Grayscale", I have to fix all the cloned jobs afterwards.

**Comment by gheinrich** [comment]
Thanks for the bug report @flx42 

This should be fixed in #714

**Comment by jmancewicz** [comment]
The clone mechanism stores the form data state, not the results.  The clone fills the form, and it is not possible to fill the form using the job state.  So, the job name is stored twice, and when it's edited, it only is changing the job._name.  That's why you're seeing this happen.

The complicating case will be using parameter sweep. If the name in the for is MySweep, and learning rate and batch size are swept, the names produced will be something like:
