### ISSUE TITLE
About manual pre-processing.

### ISSUE THREAD

**Issue by oanoelsis** [NVIDIA/DIGITS#715]
I trained my network in DIGITS. And deploy it my c++ framework with DIGITS caffemodel. And result is 1.X % worse than DIGITS result. I think reason is in the image preprocessing step. 

I used gray image. 
resize it by cv::resize()    {here, default option is INTER_LINEAR and DIGITS use image = scipy.misc.imresize(image, (height, width), 'bilinear') is it different?}

I used mean image subtraction.
so load mean.binaryproto.
And resized image convert to CV_32FC1.
And subtract them.

I think problem can occur at resize step. 
And if it is problem, I want know how can I implement c++ classifier with DIGITS caffemodel.

**Comment by lukeyeager** [comment]
Sorry for the slow response!

If you're using a different resizing method then the model performance will almost certainly not be "worse" - you'll just get different results for the same images. It sounds like you already have a C++ classifier with a DIGITS caffemodel - you don't really need to match DIGITS's output in order to have a working system.

However, it's nice to be able to verify that you're not doing anything wrong. So let's see if we can figure out your problem.

From OpenCV's documentation:
> INTER_LINEAR - a bilinear interpolation (used by default)

That sounds like it should be the same as `scipy`'s "bilinear" to me. So I doubt the resizing algorithm is your problem.

> And resized image convert to CV_32FC1.

My guess is that you are converting your image to BGR, while the mean image is in RGB (or vice versa).

Try using the classification example under `/examples/classification/` and see if you can reproduce the results there. If so, check these functions to see how DIGITS resizes images and how Caffe's `caffe.io.Transformer` gets set up.
