### ISSUE TITLE
Image visualization

### ISSUE THREAD

**Issue by pansk** [NVIDIA/DIGITS#721]
With torch, images are fed into the network as BGR (I assume), but RGB convention when displaying intermediate results, so intermediate results show up in false colors.

To show the issue, I created a network with just one multiply(1) layer, here's the inference result:

![lenabgrrgb](https://cloud.githubusercontent.com/assets/1263535/14942134/1f186742-0fb4-11e6-919e-963e182373f3.png)

**Comment by gheinrich** [comment]
Thanks for the bug report Marco. Torch receives data in RGB order. Caffe receives them in BGR order. Since the visualization routine was originally written for Caffe it is doing an unnecessary conversion from BGR to RGB in the Torch case. The issue should be fixed in #722. Can you try please?

Thanks!

**Comment by pansk** [comment]
I'll be back in office on Wednesday, is it ok?

**Comment by gheinrich** [comment]
I have updated the commit to address Luke's comment. @pansk if you can try this on Wednesday I think it's fine, thanks!

**Comment by pansk** [comment]
It works, thank you!
