### ISSUE TITLE
Digit's homepage job management reports 'Running' when it's 'Waiting'

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#729]
Title says it all. Recreate by creating a queue of jobs that exceed the amount of available GPU's. They will all say that they are running, but when you click on them they say 'Waiting'.

**Comment by gheinrich** [comment]
Thanks for the feedback @TimZaman . Technically, the status of all `ModelJob`'s is `running`. However it is true that for the job at the rear of the queue, the status of its `TrainTask` is `waiting` because it is waiting for a spare GPU.

I am not sure how to best represent both the state of the job and the state of its tasks on the main page.

cc @jmancewicz for advice. Thanks!
