### ISSUE TITLE
`yaml.h: No such file or directory` when building caffe 0.14

### ISSUE THREAD

**Issue by mikepcw** [NVIDIA/DIGITS#774]
In amongst the build output is nestled this:
```c
Installing collected packages: pyyaml
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
    skipping 'ext/_yaml.c' Cython extension (up-to-date)
  Could not find .egg-info directory in install record for pyyaml>=3.10
Successfully installed pyyaml
Cleaning up...
```
    
Even though the compilation terminates, it appears to install pyyaml fine.
Subsequent invocations return that pyyaml is already satisfied and testing DIGITS caffe based training with the given examples yields no impact errors during operation.

Is this safe to ignore?

**Comment by TimZaman** [comment]
Hi Mike. You're on Ubuntu 14.04? 

I do not think YAML is a core part of caffe, and since Digits does not use it, it is not a dependency in practice. However, Caffe requires this as part of their documentation, examples, external scripts, etc. So this explains why this has no impact during operation. For further reference, your problem is that you need to install a dependency your dependency depends on 👍 

I think python needs a dependency library you do not have, and python cannot install by itself. Therefore you probably need to (1) remove your broken pyyaml (2) install the C++ yaml library (3) re-install pyyaml
Or:

1. `pip uninstall pyyaml`
2. `sudo apt-get install libyaml-cpp-dev`
3. `pip install pyyaml`

Alternatively, you can install pyyaml systemwide without pip

`sudo apt-get install python-yaml`

It worries me pyyaml says it is installed correctly while I do not think this is the case.

**Comment by mikepcw** [comment]
> Strictly speaking, this is a Caffe (https://github.com/BVLC/caffe) issue and not a Digits issue
You are correct. Should I log an issue with them too?

**Comment by TimZaman** [comment]
The actual issue imo seems to be in pyyaml; claiming success when it fails. Did the above (1) (2) (3) solve your issue?

**Comment by mikepcw** [comment]
Actually no... at (1) it says 
`Can't uninstall 'PyYAML'. No files were found to uninstall.`

**Comment by TimZaman** [comment]
Perfect! It says it cannot uninstall it because it is not installed, which was the purpose of (1), hence you can skip (1) and confidently proceed to (2).

**Comment by mikepcw** [comment]
When I run the `cat python/requirements.txt | xargs -n1 sudo pip install` line from the nvcaffe instructions, it is says `Requirement already satisfied... : pyyaml>=3.10 ...`

**Comment by TimZaman** [comment]
Good, I am confident everything will work. If you find something that's broken and got to do with YAML, raise an issue on the BLVC Caffe repo.

**Comment by mikepcw** [comment]
Sorry, confusion. I haven't done any of (1)...(3) yet it says they are satisfied.
i.e. at the same time as saying nothing to uninstall, it's also saying satisfied!

**Comment by TimZaman** [comment]
Okay so it turns out that a pure python version of pyyaml exists without a dependency on libyaml, which you don't have. That means it did in fact install correctly, but you have a native pure python version of it! Confusing indeed, but case closed.

**Comment by mikepcw** [comment]
Awesome. I'm happy.
Cheers.
