### ISSUE TITLE
Instructions for Installation on a Mac

### ISSUE THREAD

**Issue by abhisheksimhadri** [NVIDIA/DIGITS#88]
Hi

Any instructions on installation on a Mac? It does in the Readme that it was tested and worked in Mac OSX. 

thanks

**Comment by lukeyeager** [comment]
See #87

**Comment by abhisheksimhadri** [comment]
Got it ... thank you 
 


     On Monday, 27 April 2015 10:17 PM, Luke Yeager <notifications@github.com> wrote:
   

 See #87—

**Comment by abhisheksimhadri** [comment]
Hey ... the graphviz and gunicorn work fine. 

The requirements are also easily installed with pip 

running the server becomes a problem:

runme.sh doesn't work because the executable in the third line - digits/devserver doesn't run on OS X

manually running ./digits-devserver throws the following error:

Traceback (most recent call last):
  File "./digits-devserver", line 8, in <module>
    from gevent import monkey; monkey.patch_all()
ImportError: No module named gevent

However the module is installed with pip and works on importing gevent on the python prompt

**Comment by lukeyeager** [comment]
> runme.sh doesn't work

The web installer is definitely not going to work on OSX. All of those binaries are built for Ubuntu 14.04. Try using the installation instructions in the README instead and see if you still have the gevent problem.

**Comment by abhisheksimhadri** [comment]
Install worked fine. 

The server doesn't start either by using digits-devserver or digits-server 

Was anyone able to get it running on Mac OS X (Yosemite)???

**Comment by lukeyeager** [comment]
@abhisheksimhadri, did you figure it out? Several people have gotten it to work on OSX, and I haven't heard that they needed to do anything particularly difficult. It seems like you may have skipped [this step](https://github.com/NVIDIA/DIGITS/blob/52f334c2571cdc6e7793a60a74ab0f3e5ff1dd9e/docs/InstallCaffe.md#python-dependencies).

**Comment by abhisheksimhadri** [comment]
@lukeyeager .. Nope. Couldn't get it to work. caffe works fine. the lenet and mnist examples also run without a hitch. Also able to configure the relu layer etc. 

However there seems to be some problem with the python wrapper. unable to import caffe. Also unable to run the DIGITS server. same problem ... no module named gevent

**Comment by lukeyeager** [comment]
You're going to have to be a little more specific with your bug report. Is `unable to import caffe` the actual error you're getting? When I built Caffe on a Mac, I ran into this issue: https://github.com/BVLC/caffe/issues/591. My guess is you need to adjust your Makefile.config to make sure you're using brew's python instead of the system standard version.

You're getting `no module named gevent` because you didn't install gevent. `pip install gevent` will install just that module. Following [these instructions](https://github.com/NVIDIA/DIGITS/blob/60a4652856fda3d7f104d5ce8c98ee304c3c446a/README.md#python-dependencies) will ensure that you have all the python dependencies you need.
