### ISSUE TITLE
Error classify a large number of imagelist

### ISSUE THREAD

**Issue by shinfo001** [NVIDIA/DIGITS#920]
If in the next command give 5000 of the image list
Error comes out.

`curl **. **. **. ** / models / images / classification / classify_many.json ..`
..
Failed to connect to DIGITS
..

No problem if the 10 or so of the image. It seems to be timed out.
Is a workaround available?

**Comment by gheinrich** [comment]
Hello, the workaround is to provide a smaller image list. However if you are using the production server (`digits-server`) you might want to try adding a `timeout= XX` to `/usr/share/digits/gunicorn_config.py`. You can also try the development server (`digits-devserver`).

**Comment by IsaacYangSLA** [comment]
@shinfo001 , in addition to what @gheinrich suggested, can you try these two?  1. curl to port 34448 directly to skip nginx.  2. Add proxy_read_timeout 3600s; to two locations inside nginx.site.  That file can be in /etc/nginx/sites-enabled.  You can identify the one used by DIGITS from its content.

I guessed you might receive 504 gateway timeout when trying classifying 5000 images.  That's why I suggest the above tests.

**Comment by shinfo001** [comment]
Thank you for the advice.
Anyway, it could be resolved in a way that runs by dividing list file.

I'm going to go try the other way.

**Comment by paras42** [comment]
BTW, I did the above suggestions on Digits 4.0, after which I was able to extend the timeout period and was able to test a few thousand cases for inference, which worked.

However, I upgraded to 5.0, and running into the same problem.  I went ahead and altered the  /etc/nginx/sites-enabled file as indicated above, and used port :34448.  The only thing is that I couldn't locate the  "/usr/share/digits/gunicorn_config.py" file in 5.0 (assuming due to differences in 5.0).  As such I couldn't alter the timeout= XX in that file.  Anyone know how to modify the timeout in 5.0 to allow for inference on larger amount of cases?

**Comment by kunalsrkr** [comment]
hi,
@gheinrich  i have edited the gunicorn_config.py file and add the timeout option there. but it is showing Classification failed, see job log,( ERROR: error code 1).after that I undo the change, but still it showing the same error.InferenceError: Unable to load any image from file ''/usr/share/digits/digits/jobs/ here.As the file pointing here is not present in that directory.Please help

**Comment by kunalsrkr** [comment]
@gheinrich how to undo the change
